// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package tutorial

import (
	"database/sql"
	"time"
)

type Author struct {
	ID        int64
	CreatedAt time.Time
	Name      string
	Bio       sql.NullString
}
